cloud:
    aws:
        credentials:
            accessKey: accessKey
            secretKey: secretKey
        region:
            auto: false
            static: ap-northeast-2
        stack:
            auto: false