spring:
  profiles:
      active: local
---
spring:
    config:
        activate:
            on-profile: local

---
spring:
    config:
        activate:
            on-profile: prod
amazon:
    aws:
        accessKey: test
        secretKey: test

